


export const resetActionTypes = {
        AUTH_RESET_ACTION: 'AUTH_MESSAGE_RESET_ACTION',
    }


export const loginActionType = {
        SUCCESS_ACTION: "LOGIN_SUCCESS_ACTION",
        REQUEST_ACTION: "LOGIN_REQUEST_ACTION",
        FAILED_ACTION: "LOGIN_FAILED_ACTION",
        SESSION_EXPIRED_ACTION: 'SESSION_EXPIRED_ACTION'
}
    